### ISSUE TITLE
ISSUES WITH SOUNDS

### ISSUE THREAD

**Issue by Phoenix-99** [Boy0000/BlockSounds-ItemsAdder#1]
Hi, I'm having issues, I have custom baobab woods, log, and more, but sounds doesn't works, i dont know why!! i hope you can help me.
sound just works when i hit the block but the rest sound doesn't works, here is a short video from imgur (don't forget turn on the audio)
https://imgur.com/ZRVhGZp

also, i'll put the config files
![image](https://user-images.githubusercontent.com/63762282/202931514-58fe91a1-b256-473e-aa4c-78127906a157.png)
 but that error it doesn't happens with other block, called baobab leaves that is in the same name space
as you can see in the next video
https://imgur.com/ZKMxnDr

and this is the config of baobab leaves 
![image](https://user-images.githubusercontent.com/63762282/202932147-719c454b-d68a-4533-9719-d4706b5b4788.png)

i hope you can help me with this!

**Comment by Boy0000** [comment]
Block.wood.x is replaced with an empty sound to allow for custom sounds. If you want wood, ritht now you need to use required.wood.x

**Comment by Phoenix-99** [comment]
Thanks you so much!! fixed it!!!
