### ISSUE TITLE
REAL_TRANSPARENT block type doesn't play STEP and FALL sound

### ISSUE THREAD

**Issue by Millionary** [Boy0000/BlockSounds-ItemsAdder#2]
I used the plugin and those 2 sounds are not working, i guess that's because of the block type. This is the config for the sound specific propertie:

        sound: 
          break:
            name: block.grass.break
            volume: 1
            pitch: 0.8
          place:
            name: block.grass.place
            volume: 1
            pitch: 0.8
          hit:
            name: block.grass.hit
            volume: 1
            pitch: 0.5
          step:
            name: block.grass.hit
            volume: 1
            pitch: 0.8        
          fall:
            name: block.grass.hit
            volume: 1
            pitch: 0.8   
            
It also doesn't work with 'block.grass.step' and 'block.grass.fall'.

**Comment by AllayBreeze** [comment]
This issue still exists, but only on some chorus plant blocks that have lower hitboxes. I think it's worth checking again.

The sound can be played normally by standing at the edge of other normal height blocks and touching the edge of a lower height chorus plant block. But once you completely step on these kinds of chorus plant blocks and your height decreases, there will be no walking sounds.

**Comment by Boy0000** [comment]
Seeing as i havent done anything to chorus plant blocks it makes sense

**Comment by Boy0000** [comment]
@Millionary @AllayBreeze sorry for the delay, this should now be fixed.
Please verify and close the issue 👍
