### ISSUE TITLE
Block place sound plays when right-clicking on blocks with items

### ISSUE THREAD

**Issue by AhmetJR** [Boy0000/BlockSounds-ItemsAdder#5]
Block place sound plays when right-clicking on blocks with items
https://cdn.discordapp.com/attachments/923248222368067676/1067949690940825760/2023-01-26_00-34-05.mp4

**Comment by Boy0000** [comment]
@AhmetJR this should be fixed in 1.4 aka latest release
Please confirm and close this 👍
