### ISSUE TITLE
Doesn't seem to be working on 1.19.3

### ISSUE THREAD

**Issue by Happyperson3796** [Boy0000/BlockSounds-ItemsAdder#6]
It doesn't seem to do anything with this:
items:
  jungle_log_snowy:
    display_name: Snowy Jungle Log
    resource:
      generate: true
      material: PAPER
      textures:
        - minecraft:block/jungle_log_top.png
        - block/jungle_log_snowy.png
        - block/jungle_log_snowy.png
        - block/jungle_log_snowy.png
        - minecraft:block/jungle_log_top.png
        - block/jungle_log_snowy.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        break_tools_whitelist:
          - _AXE
        hardness: 2
        blast_resistance: 1
        block_sounds:
          place_sound: block.required.wood.place
          break_sound: block.required.wood.break
          hit_sound: block.required.wood.hit
          step_sound: block.required.wood.step
          fall_sound: block.required.wood.fall

**Comment by Boy0000** [comment]
@Happyperson3796 doesnt work because ur not following the config format
Please look on the spigot page as it details everything

**Comment by Happyperson3796** [comment]
You should probably update the example in the config.json, I followed the format found there.

**Comment by Boy0000** [comment]
it was never meant to generate and forgot about it. have now deleted it
follow the instructions on the spigot page
